package com.demo.model;

public enum Status {
    // Product Statuses
    PENDING_AVAILABILITY_CONFIRMATION,
    AVAILABILITY_CONFIRMED,
    PRODUCTS_UNAVAILABILITY,
    PRODUCTS_RESTORED,

    // Shipment Statuses
    PENDING_SHIPMENT_ARRANGEMENT,
    PENDING_SHIPMENT_CANCELLATION,
    SHIPMENT_ARRANGED,
    SHIPMENT_ARRANGEMENT_FAILED,
    SHIPMENT_CANCELLED,

    // Order Statuses
    CREATED,
    PENDING_COMPLETION,
    COMPLETED,
    PENDING_CANCELLATION,
    CANCELLED,

    // Payment Statuses
    PENDING_PAYMENT,

    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,

    // Outbox
    PENDING_PUBLISHING, PUBLISHED, PUBLISHING_FAILED
}
