package com.demo.service;

import com.demo.common.payload.Payload;
import com.demo.model.Payment;
import com.demo.model.Status;

/**
 * Service interface for the core business logic of managing payments.
 * <p>
 * This contract defines the primary operations for creating and
 * retrieving payment records. It is used by the
 * {@link com.demo.component.PaymentCommandsHandler} to persist
 * the outcome of a payment attempt.
 */
public interface PaymentService {

    /**
     * Creates and saves a new payment record.
     * <p>
     * This method is called by the command handler *after* the payment
     * has been processed (or failed) to create an immutable log
     * of the transaction.
     *
     * @param processPaymentPayload The payload from the ProcessPaymentCommand}.
     * @param status                The final status of the transaction (e.g., PAYMENT_SUCCEEDED, PAYMENT_FAILED).
     * @return The newly persisted {@link Payment} entity.
     */
    Payment save(Payload processPaymentPayload, Status status);

    /**
     * Retrieves a payment record by its unique transaction ID
     * (which is typically generated by the payment gateway).
     *
     * @param transactionId The external transaction ID.
     * @return The corresponding {@link Payment} entity, or null if not found.
     */
    Payment retrieve(String transactionId);

}
