package com.demo.model;

import com.demo.common.payload.Payload;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * Represents a "Dead-Letter Message" that has failed processing.
 * <p>
 * This entity is the aggregate root for the DLT Service. It stores a
 * copy of any message that has failed all retry attempts in another
 * microservice. This creates a persistent log of failures that
 * administrators can review and manually re-trigger or resolve.
 *
 * @see com.demo.service.DltMessageService
 */
@Entity
@Table(name = "dlt_messages")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class DltMessage {

    /**
     * The unique primary key for this DLT record.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * The original unique ID of the failed message.
     * This ID is used for idempotency checks in the consumer services.
     * (Note: There appears to be a typo in the @Column name, "message_im").
     */
    @Column(name = "message_id", nullable = false)
    private UUID messageId;

    /**
     * The saga's correlation ID (usually the Order ID).
     * This links the failed message back to the specific saga instance.
     */
    @Column(name = "correlation_id", nullable = false)
    private UUID correlationId;

    /**
     * The type of the failed message (e.g., "EVENT: ORDER_CREATED",
     * "COMMAND: PROCESS_PAYMENT").
     */
    @Column(nullable = false)
    private String type;

    /**
     * The current resolution status of this DLT message
     * (e.g., UNRESOLVED, RESOLVED).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Status status;

    /**
     * A human-readable description of the failure, generated by
     * {@link com.demo.utility.Utils#determineDescription(String)}.
     * (e.g., "PAYMENT-SERVICE couldn't process PROCESS_PAYMENT.").
     */
    @Column(nullable = false)
    private String description;

    /**
     * The full JSON payload of the original failed message.
     * This is crucial for debugging and re-processing.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    private Payload payload;

    /**
     * Timestamp of when this DLT message was first received and
     * registered by the DLT service.
     */
    @Column(name = "received_at", nullable = false)
    private Instant receivedAt;

    /**
     * Timestamp of the last update to this DLT record
     * (e.g., when an admin changes its status to RESOLVED).
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

}
